name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Lint
        run: composer lint

      - name: PHPCS (WordPress)
        run: composer phpcs
